name: pause
description: "pause-clap"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 데이터 모델링 자동화 라이브러리
  json_annotation: ^4.8.1
  # 파이어베이스 관련 라이브러리
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  # 상태관리 라이브러리
  get: ^4.6.6
  # 이미지 관련 라이브러리
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  # 내부 저장소 라이브러리
  shared_preferences: ^2.2.2
  # 카카오 로그인
  kakao_flutter_sdk: ^1.8.0
  # 네이버 로그인
  flutter_naver_login: ^1.8.0
  # 애플 로그인
  sign_in_with_apple: ^5.0.0
  # 구글 로그인
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/logo/
    - assets/logo/social/
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
